
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-04
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-PurgeLogsButton","number":50,"title":"added button to frontend","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/50"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-PersonalSchedules-bug1","number":48,"title":"Alvin - Personal Schedules Bug","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/48"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-Jobs-By-Id","number":47,"title":"Alvin - GET Endpoint - by job id","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/47"},{"author":{"id":"U_kgDOBtOw_A","is_bot":false,"login":"PiyushJadhav","name":""},"headRefName":"pj-dropdown","number":42,"title":"DropdownSelector Component that allows the user to select a subject area","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/42"}]
