
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-04
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-04
pull_requests: [{"author":{"id":"U_kgDOB_ueCQ","is_bot":false,"login":"nilay-kundu","name":"Nilay Kundu"},"headRefName":"nk-finalsinfo","number":41,"title":"Finals info backend","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/41"},{"author":{"id":"U_kgDOBtOw_A","is_bot":false,"login":"PiyushJadhav","name":""},"headRefName":"pj-sectiontable2","number":38,"title":"SectionTable.js better Stryker testing ","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/38"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-StrykerArrowFunction","number":37,"title":"Test Added to Fix Stryker Exception on Arrow Function","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/37"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-updatesUpdateTable2","number":34,"title":"Created UpdateTable component for updates","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/34"}]
