
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-04
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-04
pull_requests: [{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-strykerException3","number":30,"title":"Removed Stryker Exception in Section Instructor Table","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/30"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-updatedOptionalDescription","number":29,"title":"Description optional on personal schedule - UPDATED","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/29"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-reduceClutter","number":24,"title":"Reduced clutter in log from course update jobs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/24"},{"author":{"id":"U_kgDOB_ueCQ","is_bot":false,"login":"nilay-kundu","name":"Nilay Kundu"},"headRefName":"nk-BackendError","number":23,"title":"User-friendly error message to adding 2 sections of same course","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/23"},{"author":{"id":"U_kgDOBtOw_A","is_bot":false,"login":"PiyushJadhav","name":""},"headRefName":"pj-getActiveQuarterList","number":20,"title":"PJ - getActiveQuarterList","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/20"}]
