
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-04
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-04
pull_requests: [{"author":{"id":"U_kgDOBtOw_A","is_bot":false,"login":"PiyushJadhav","name":""},"headRefName":"pj-sectiontable","number":36,"title":"SectionTable.js better Stryker test","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/36"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"Jackie-updatesUpdateTable2","number":34,"title":"Created UpdateTable component for updates","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-04/pull/34"}]
